language: ruby
rvm:
  - ruby-2.4.10
  - ruby-2.5.9
  - ruby-2.6.7
  - ruby-2.7.3
  - jruby-9.2.19.0
services:
  - postgresql
bundler_args: --without development
before_install:
  - rm -f Gemfile.lock
before_script:
  - psql -c 'create database sequel_seed_test;' -U postgres
script:
  - bundle exec rake
