language: ruby
rvm:
  - ruby-2.1.10
  - ruby-2.2.10
  - ruby-2.3.8
  - ruby-2.4.6
  - ruby-2.5.5
  - ruby-2.6.3
  - jruby-9.1.9.0
services:
  - postgresql
before_install:
  - rm -f Gemfile.lock
before_script:
  - psql -c 'create database sequel_seed_test;' -U postgres
script:
  - bundle exec rake
